<?php

/**
 * @file
 * Contains stripe_registration.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Url;
use Stripe\Customer;
use Stripe\Plan;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Drupal\stripe_registration\StripeRegistrationService;

/**
 * Implements hook_help().
 */
function stripe_registration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the stripe_registration module.
    case 'help.page.stripe_registration':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Facilitates paid site registration via a Stripe subscription plan.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_form_alter().
 */
function stripe_registration_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  switch ($form_id) {
    case 'user_register_form':
      if (\Drupal::config('stripe_registration.settings')->get('registration')) {
        stripe_registration_subscribe_form($form, $form_state, $form_id);
      }
      break;

    case 'stripe_subscribe_form':
      stripe_registration_subscribe_form($form, $form_state, $form_id);
      break;

    case 'stripe_api_admin_form':
      stripe_registration_admin_form($form, $form_state, $form_id);

      break;
  }
}

function stripe_registration_admin_form(array &$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('stripe_registration.settings');
  /** @var \Drupal\stripe_api\StripeApiService $stripe_api */
  $stripe_api = \Drupal::service('stripe_api.stripe_api');

  $form['registration'] = [
    '#type' => 'checkbox',
    '#title' => t('Allow users to subscribe to plans during Drupal account registration'),
    '#description' => t('If checked, users will be able to subscribe to a plan during user account registration.'),
    '#default_value' => $config->get('registration') ? $config->get('registration') : FALSE,
  ];
  $form['redirect'] = [
    '#type' => 'checkbox',
    '#title' => t('Redirect users to Subscription page after login'),
    '#description' => t('If checked, users will immediately be redirected to the Subscription page after login if 1) They do not already have a subscription, and 2) The request does not already have a redirect query parameter.'),
    '#default_value' => $config->get('redirect') ? $config->get('redirect') : FALSE,
  ];

  $form['actions']['sync-plans'] = [
    '#type' => 'submit',
    '#value' => t('Sync plans from Stripe'),
    '#description' => t('This will create new plans and removed plans that no longer exist upstream.'),
    '#submit' => ['stripe_registration_sync_plans_submit'],
    '#weight' => 100,
    '#disabled' => !$stripe_api->getApiKey(),
  ];

  $form['#submit'][] = 'stripe_registration_admin_form_submit';
}

function stripe_registration_admin_form_submit(array &$form, FormStateInterface $form_state) {
  $config = \Drupal::configFactory()->getEditable('stripe_registration.settings');
  $config->set('registration', $form_state->getValue('registration'))->save();
  $config->set('redirect', $form_state->getValue('redirect'))->save();
}

function stripe_registration_sync_plans_submit(array &$form, FormStateInterface $form_state) {
  /** @var StripeRegistrationService $stripe */
  $stripe = \Drupal::service('stripe_registration.stripe_api');
  $stripe->syncPlans(TRUE);
}

/**
 * Implements hook_entity_extra_field_info().
 */
function stripe_registration_entity_extra_field_info() {
  $fields['user']['user']['form']['stripe_registration_plans'] = [
    'label' => t('Stripe registration plan'),
    'description' => t('a plan selector.'),
    'weight' => 5,
  ];
  $fields['user']['user']['form']['stripe_registration_payment'] = [
    'label' => t('Stripe registration payment'),
    'description' => t('Payment field.'),
    'weight' => 5,
  ];

  return $fields;
}

/**
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 */
function stripe_registration_subscribe_form(&$form, FormStateInterface $form_state, $form_id) {

  /** @var \Drupal\stripe_registration\StripeRegistrationService $stripe_registration */
  $stripe_registration =  \Drupal::service('stripe_registration.stripe_api');
  $stripe_api =  \Drupal::service('stripe_api.stripe_api');

  $plans = $stripe_registration->loadLocalPlanMultiple();
  if (!$plans) {
    $form['message'] = [
      '#type' => 'markup',
      '#markup' => t('There are no plans to which you may subscribe.'),
    ];

    return FALSE;
  }

  $form['#attached']['library'][] = 'stripe_registration/stripe.stripejs';
  $form['#attached']['library'][] = 'stripe_registration/stripe.jquery.payment';
  $form['#attached']['library'][] = 'stripe_registration/checkout';
  $form['#attached']['drupalSettings']['stripe_registration']['publishable_key'] = $stripe_api->getPubKey();
  $form['#attached']['drupalSettings']['stripe_registration']['form_id'] = $form_id;

  /** @var Plan[] $options */
  $options = [];
  $current_site_mode = $stripe_api->getMode();
  $is_live_mode = $current_site_mode == 'live';

  /** @var \Drupal\stripe_registration\Entity\StripePlanEntity $plan */
  foreach ($plans as $plan) {
    if ($plan->livemode->value == $is_live_mode) {
      $options[$plan->plan_id->value] = $plan->name->value;
      if ($plan->data) {
        $form['#attached']['drupalSettings']['stripe_registration']['plans'][$plan->name->value] = $plan->data->getValue()[0];
      }
    }
  }

  $form['stripe_registration_plans']['plan'] = [
    '#type' => 'select',
    '#title' => t('Plan'),
    '#options' => $options,
    '#required' => TRUE,
  ];
  if (count($options) == 1) {
    $first_option = reset($options);
    $form['stripe_registration_plans']['plan']['#default_value'] = $first_option;
  }

  // By omitting a name, the user-supplied data in those fields won't be
  // passed to your server when the form is submitted. This is Stripe's
  // recommended best practice. Each element also includes a data-stripe
  // attribute added by JS and used by Stripe to identify the field. Note that
  // we cannot make these fields required if there is no name attribute.

  $form['stripe_registration_payment']['card_number'] = [
    '#type' => 'textfield',
    '#title' => t('Card number'),
    '#attributes' => [
      'data-stripe' => 'number',
    ],
    '#name' => '',
  ];
  $form['stripe_registration_payment']['exp'] = [
    '#type' => 'textfield',
    '#title' => t('MM / YYYY'),
    '#name' => '',
    '#size' => 9,
  ];
  $form['stripe_registration_payment']['cvc'] = [
    '#type' => 'textfield',
    '#title' => t('CVC'),
    '#attributes' => [
      'data-stripe' => 'cvc',
    ],
    '#name' => '',
    '#size' => 4,
  ];
  $form['stripe_registration_payment']['address_zip'] = [
    '#type' => 'textfield',
    '#title' => t('Billing zip'),
    '#attributes' => [
      'data-stripe' => 'address_zip',
    ],
    '#name' => '',
    '#size' => 5,
    '#maxlength' => 5,
  ];
  $form['stripeToken'] = [
    '#type' => 'hidden',
  ];
  $form['stripe-messages'] = [
    '#type' => 'container',
  ];

  // @todo Add validation handler.

  $form['actions']['#type'] = 'actions';
  $form['actions']['submit']['#type'] = 'submit';
  $form['actions']['submit']['#value'] = t('Subscribe');
  $form['actions']['submit']['#button_type'] = 'primary';

  $form['actions']['submit']['#validate'][] = 'stripe_registration_validate';
  $form['actions']['submit']['#submit'][] = 'stripe_registration_submit';
}

/**
 * Validate callback for user_register_form.
 */
function stripe_registration_validate($form, FormStateInterface $form_state) {
  // Most form validation is performed via JavaScript. The remaining validation
  // must be performed by the Stripe API. Unfortunately, that means that we must
  // submit information to Stripe in the validation method. If we performed this
  // submission in a submit handler, we would not be able to set form errors.
  /** @var \Drupal\stripe_registration\StripeRegistrationService $stripe */
  $stripe =  \Drupal::service('stripe_registration.stripe_api');
  $messenger = \Drupal::messenger();

  try {
    if (empty($form_state->getValue('stripeToken'))) {
      throw new \Exception("Stripe token is missing!");
    }
    if (empty($form_state->getValue('uid'))) {
      throw new \Exception("Uid is missing!");
    }

    $uid = $form_state->getValue('uid');
    $user = \Drupal\user\Entity\User::load($uid);
    $customer = \Stripe\Customer::create(array(
      "source" => $form_state->getValue('stripeToken'),
      "plan" => $form_state->getValue('plan'),
      "email" => $user->getEmail(),
    ));

    if ($customer instanceof Customer) {
      /** @var Customer $user */
      $user = \Drupal::entityTypeManager()->getStorage('user')->load($form_state->getValue('uid'));
      $user->set('stripe_customer_id', $customer->id);
      $user->save();

      foreach ($customer->subscriptions->data as $subscription) {
        if ($subscription->status === 'active') {
          $stripe->createLocalSubscription($subscription);
          $messenger->addMessage(t("You have successfully subscribed to the @plan_name plan.", ['@plan_name' => $form_state->getValue('plan')]), 'status');
        } else {
          throw new Exception($subscription->status);
        }
      }
    }
  } catch (\Exception $e) {
    \Drupal::logger('stripe_registration')
      ->error(t("Could not subscribe user @uid to @plan plan, error:\n@stripe_error.", [
        '@uid' => $form_state->getValue('uid'),
        '@plan' => $form_state->getValue('plan'),
        '@stripe_error' => $e->getMessage(),
      ]));

    $message = t("Subscription could not be activated, please try again. Message received: @error", ['@error' => $e->getMessage()]);

    $messenger->addMessage(t("@stripe_error", [
      '@stripe_error' => $message,
    ]), 'error');

    $form_state->setErrorByName('stripe-messages', $message);
  }
}

/**
 * Submit callback for user_register_form.
 */
function stripe_registration_submit($form, FormStateInterface $form_state) {
  $form_state->setRedirectUrl(new Url('stripe_registration.my_subscriptions'));
}

/**
 * Implements hook_entity_field_access().
 */
function stripe_registration_entity_field_access($operation, \Drupal\Core\Field\FieldDefinitionInterface $field_definition, \Drupal\Core\Session\AccountInterface $account, \Drupal\Core\Field\FieldItemListInterface $items = NULL) {
  // Prevent anyone from modifying or viewing the value of stripe_customer_id via the UI.
  if ($field_definition->getName() == 'stripe_customer_id') {
    return AccessResult::forbidden();
  }

  return AccessResult::neutral();
}

/**
 * Implements hook_user_login().
 */
function stripe_registration_user_login($account) {
  // Un-subscribed users should be redirected to the subscribe page, unless a
  // redirect parameter is already defined.
  $config = \Drupal::config('stripe_registration.settings');
  $destination_param = \Drupal::request()->query->get('destination');
  if ($config->get('redirect') && !$destination_param) {
    /** @var StripeRegistrationService $stripe_registration */
    $stripe_registration =  \Drupal::service('stripe_registration.stripe_api');
    if (!$stripe_registration->userHasStripeSubscription($account)) {
      $url = Url::fromRoute('stripe_registration.user.subscriptions.viewall', ['user' => $account->id()]);
      $response = new RedirectResponse($url->toString());
      $response->send();

      return FALSE;
    }
  }
}

/**
 * Implementes hook_cron(). Use this to sync users whose subscription has expired.
 */
function stripe_registration_cron() {
  $expired_subscription_ids = Drupal::entityQuery('stripe_subscription')
    ->condition('status', 'active')
    ->condition('current_period_end', time(), '<')
    ->range(0, 10)
    ->execute();

  /** @var StripeRegistrationService $stripe */
  $stripe = \Drupal::service('stripe_registration.stripe_api');

  foreach ($expired_subscription_ids as $subscription_id) {
    try {
      $stripe->syncRemoteSubscriptionToLocal($subscription_id);
    } catch (\Exception $exception) {
      Drupal::logger('stripe_registration')->error('Something went wrong: ' . $exception->getMessage());
    }
  }
}

// Licensing:
// @todo Allow purchasing of licenses for single nodes.

// allow licensing of a role or a node? abstract a la kris v?
